kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  namespace: default

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: local-pv
  storageClassName: local-storage
  volumeMode: Filesystem
