server:
  port: 8080
spring:
  servlet:
    multipart:
      # 单个文件最大值
      max-file-size: 1024MB
      # 多个文件最大值
      max-request-size: 1024MB
  datasource:
    url: jdbc:mysql://10.51.72.167:3306/training
    username: root
    password: abcDEF123___
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    local-date-time-format: yyyy-MM-dd HH:mm:ss
    local-date-format: yyyy-MM-dd
    local-time-format: HH:mm:ss
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 0eea41129e6b55a01323
            clientSecret: 6d3a0552460982205cfe9042f03f19331a1232f7


management:
  endpoints:
    web:
      exposure:
        include: info, health, mappings