spring:
  datasource:
    url: jdbc:mysql://10.51.72.167:3306/plain_a
    username: root
    password: abcDEF123___
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    local-date-time-format: yyyy-MM-dd HH:mm:ss
    local-date-format: yyyy-MM-dd
    local-time-format: HH:mm:ss
