spring:
  datasource:
    url: jdbc:mysql://localhost/plain_a
    username: root
    password: abcDEF123___
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
