apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
  labels:
    pv: mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "models"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-volume-claim-mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: mysql