commonLabels:
  k8s-app: training
resources:
- deployment.yml
- service.yml
- ingress.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: harbor.hknaruto.com/yeqiang/training
  newTag: master.2191e0f
