apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-harbor-registry
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local: # local类型
    path: /k8s-persistent-volume/harbor-registry
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 10.51.72.167

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-harbor-registry
  namespace: harbor
  labels:
    app: harbor
    chart: harbor
    component: registry
    heritage: Helm
    release: release
  annotations:
    helm.sh/resource-policy: keep
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"helm.sh/resource-policy":"keep"},"labels":{"app":"harbor","chart":"harbor","component":"registry","heritage":"Helm","release":"release"},"name":"release-harbor-registry","namespace":"harbor"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"5Gi"}}}}
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: local-pv-harbor-registry
  storageClassName: local-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-harbor-chartmuseum
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local: # local类型
    path: /k8s-persistent-volume/harbor-chartmuseum
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 10.51.72.167

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-harbor-chartmuseum
  namespace: harbor
  labels:
    app: harbor
    chart: harbor
    component: chartmuseum
    heritage: Helm
    release: release
  annotations:
    helm.sh/resource-policy: keep
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"helm.sh/resource-policy":"keep"},"labels":{"app":"harbor","chart":"harbor","component":"registry","heritage":"Helm","release":"release"},"name":"release-harbor-chartmuseum","namespace":"harbor"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"5Gi"}}}}
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: local-pv-harbor-chartmuseum
  storageClassName: local-storage
  volumeMode: Filesystem


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-harbor-jobservice
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local: # local类型
    path: /k8s-persistent-volume/harbor-jobservice
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 10.51.72.167

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-harbor-jobservice
  namespace: harbor
  labels:
    app: harbor
    chart: harbor
    component: jobservice
    heritage: Helm
    release: release
  annotations:
    helm.sh/resource-policy: keep
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"helm.sh/resource-policy":"keep"},"labels":{"app":"harbor","chart":"harbor","component":"registry","heritage":"Helm","release":"release"},"name":"release-harbor-jobservice","namespace":"harbor"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"1Gi"}}}}
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: local-pv-harbor-jobservice
  storageClassName: local-storage
  volumeMode: Filesystem


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-harbor-database
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local: # local类型
    path: /k8s-persistent-volume/harbor-database
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 10.51.72.167

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-harbor-database
  namespace: harbor
  labels:
    app: harbor
    chart: harbor
    component: database
    heritage: Helm
    release: release
  annotations:
    helm.sh/resource-policy: keep
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"helm.sh/resource-policy":"keep"},"labels":{"app":"harbor","chart":"harbor","component":"registry","heritage":"Helm","release":"release"},"name":"release-harbor-database","namespace":"harbor"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"1Gi"}}}}
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: local-pv-harbor-database
  storageClassName: local-storage
  volumeMode: Filesystem


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-harbor-redis
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local: # local类型
    path: /k8s-persistent-volume/harbor-redis
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 10.51.72.167

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-harbor-redis
  namespace: harbor
  labels:
    app: harbor
    chart: harbor
    component: redis
    heritage: Helm
    release: release
  annotations:
    helm.sh/resource-policy: keep
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"helm.sh/resource-policy":"keep"},"labels":{"app":"harbor","chart":"harbor","component":"registry","heritage":"Helm","release":"release"},"name":"release-harbor-redis","namespace":"harbor"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"1Gi"}}}}
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: local-pv-harbor-redis
  storageClassName: local-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-harbor-trivy
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local: # local类型
    path: /k8s-persistent-volume/harbor-trivy
  nodeAffinity: # 这里就设置了节点亲和
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 10.51.72.167

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-harbor-trivy
  namespace: harbor
  labels:
    app: harbor
    chart: harbor
    component: trivy
    heritage: Helm
    release: release
  annotations:
    helm.sh/resource-policy: keep
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"helm.sh/resource-policy":"keep"},"labels":{"app":"harbor","chart":"harbor","component":"registry","heritage":"Helm","release":"release"},"name":"release-harbor-trivy","namespace":"harbor"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"5Gi"}}}}
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: local-pv-harbor-trivy
  storageClassName: local-storage
  volumeMode: Filesystem